/*
 * Copyright 2011 Nicolas Hervé.
 * 
 * This file is part of Icy4Eclipse.
 * 
 * Icy4Eclipse is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Icy4Eclipse is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Icy4Eclipse. If not, see <http://www.gnu.org/licenses/>.
 */

package icy.icy4eclipse.templates;

import icy.icy4eclipse.core.Icy4EclipseCommonResources;
import icy.icy4eclipse.core.IcyProjectTemplate;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.core.runtime.Path;
import org.eclipse.jdt.core.IClasspathEntry;
import org.eclipse.jdt.core.JavaCore;

/**
 * @author Nicolas Hervé - n.herve@laposte.net
 * 
 */
public class NherveSingletonProjectTemplate implements IcyProjectTemplate, Icy4EclipseCommonResources {
	@Override
	public String getPluginMainClassImplementation(String pluginName, String packageName, String className) {
		StringBuffer javaFile = new StringBuffer();
		javaFile.append("package " + packageName + ";\n");
		javaFile.append("\n");

		
		javaFile.append("import icy.gui.dialog.MessageDialog;\n");
		javaFile.append("import java.awt.Dimension;\n");
		javaFile.append("import java.awt.event.ActionEvent;\n");
		javaFile.append("import java.awt.event.ActionListener;\n");
		javaFile.append("import javax.swing.JButton;\n");
		javaFile.append("import javax.swing.JPanel;\n");
		javaFile.append("import plugins.nherve.toolbox.plugin.SingletonPlugin;\n");
		javaFile.append("\n");
		javaFile.append("public class "+className+" extends SingletonPlugin implements ActionListener {\n");
		javaFile.append("\tprivate JButton aButton;\n");
		javaFile.append("\t\n");
		javaFile.append("\t@Override\n");
		javaFile.append("\tpublic void actionPerformed(ActionEvent e) {\n");
		javaFile.append("\t\t// TODO Auto-generated by Icy4Eclipse\n");
		javaFile.append("\t\tObject o = e.getSource();\n");
		javaFile.append("\n");
		javaFile.append("\t\tif (o == null) {\n");
		javaFile.append("\t\t\treturn;\n");
		javaFile.append("\t\t}\n");
		javaFile.append("\n");
		javaFile.append("\t\tif (o instanceof JButton) {\n");
		javaFile.append("\t\t\tJButton b = (JButton) o;\n");
		javaFile.append("\n");
		javaFile.append("\t\t\tif (b == aButton) {\n");
		javaFile.append("\t\t\t\tMessageDialog.showDialog(\""+pluginName+" is working fine !\");\n");
		javaFile.append("\t\t\t}\n");
		javaFile.append("\t\t}\n");
		javaFile.append("\t}\n");
		javaFile.append("\n");
		javaFile.append("\t@Override\n");
		javaFile.append("\tpublic void fillInterface(JPanel mainPanel) {\n");
		javaFile.append("\t\t// TODO Auto-generated by Icy4Eclipse\n");
		javaFile.append("\t\taButton = new JButton(\"Click me\");\n");
		javaFile.append("\t\taButton.addActionListener(this);\n");
		javaFile.append("\t\tmainPanel.add(aButton);\n");
		javaFile.append("\t}\n");
		javaFile.append("\n");
		javaFile.append("\t@Override\n");
		javaFile.append("\tpublic Dimension getDefaultFrameDimension() {\n");
		javaFile.append("\t\t// TODO Auto-generated by Icy4Eclipse\n");
		javaFile.append("\t\treturn new Dimension(400, 400);\n");
		javaFile.append("\t}\n");
		javaFile.append("\n");
		javaFile.append("\t@Override\n");
		javaFile.append("\tpublic void sequenceHasChanged() {\n");
		javaFile.append("\t\t// TODO Auto-generated by Icy4Eclipse\n");
		javaFile.append("\t}\n");
		javaFile.append("\n");
		javaFile.append("\t@Override\n");
		javaFile.append("\tpublic void sequenceWillChange() {\n");
		javaFile.append("\t\t// TODO Auto-generated by Icy4Eclipse\n");
		javaFile.append("\t}\n");
		javaFile.append("\n");
		javaFile.append("\t@Override\n");
		javaFile.append("\tpublic void stopInterface() {\n");
		javaFile.append("\t\t// TODO Auto-generated by Icy4Eclipse\n");
		javaFile.append("\t}\n");
		javaFile.append("}\n");

		return javaFile.toString();
	}

	@Override
	public String getTemplateName() {
		return "NHerve singleton";
	}

	@Override
	public String getTemplateDescription() {
		return "create a plugin based on the NHerve Toolbox library";
	}

	@Override
	public List<IClasspathEntry> getSpecificClasspathEntries() {
		ArrayList<IClasspathEntry> lst = new ArrayList<IClasspathEntry>();
		lst.add(JavaCore.newVariableEntry(new Path(ICY4ECLIPSE_HOME_VARIABLE + "/" + ICY_PLUGINS_DIR + "/nherve/toolbox/NherveToolbox.jar"), null, null));
		return lst;
	}

}
